# spring.application.name=bff-web
# bff-web/src/main/resources/application.yml
spring:
  application:
    name: bff-web
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
  servlet:
    session:
      timeout: 30m
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3307/OCO
    username: com_dev
    password: qwer1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 9103

app:
  api:
    gateway-url: http://localhost:9102
  jwtSecret: adtcapsSecretKey    